// made by Yrysa
enum AppLanguage { ru, en, kk }

class AppStrings {
  final AppLanguage language;
  const AppStrings(this.language);

  String t(String key) => _values[language]?[key] ?? _values[AppLanguage.ru]?[key] ?? key;

  static const Map<AppLanguage, Map<String, String>> _values = {
    AppLanguage.ru: {
      'app': 'Yrysa Wiki Reader',
      'discover': 'Главная',
      'day': 'Статья дня',
      'search': 'Поиск',
      'saved': 'Сохранённое',
      'social': 'Соцсеть',
      'profile': 'Профиль',
      'next': 'Следующая статья',
      'favorite_add': 'Добавить в избранное',
      'favorite_on': 'В избранном',
      'copy': 'Скопировать ссылку',
      'share': 'Поделиться',
      'open_wiki': 'Открыть Wikipedia',
      'text_up': 'Увеличить текст',
      'text_down': 'Уменьшить текст',
      'reader': 'Режим чтения',
      'github': 'GitHub автора',
      'settings': 'Настройки',
      'history': 'История',
      'favorites': 'Избранное',
      'empty_history': 'История пока пустая',
      'empty_favorites': 'Пока нет избранных статей',
      'offline': 'Нет подключения. Сохранённые статьи доступны оффлайн.',
      'try_again': 'Попробовать снова',
      'copied': 'Ссылка скопирована',
      'app_language': 'Язык приложения',
      'wiki_language': 'Язык Wikipedia',
      'theme': 'Тема приложения',
      'dark_theme': 'Тёмная тема',
      'stats': 'Статистика',
      'clear_history': 'Очистить историю',
      'clear_favorites': 'Очистить избранное',
      'about': 'О приложении',
      'version': 'Yrysa Wiki Reader 2.82.47',
      'login': 'Войти',
      'register': 'Создать аккаунт',
      'guest': 'Войти как гость',
      'friends': 'Друзья',
      'chats': 'Чаты',
      'send_friend': 'Отправить другу',
    },
    AppLanguage.en: {
      'app': 'Yrysa Wiki Reader',
      'discover': 'Discover',
      'day': 'Article of the day',
      'search': 'Search',
      'saved': 'Saved',
      'social': 'Social',
      'profile': 'Profile',
      'next': 'Next article',
      'favorite_add': 'Add to favorites',
      'favorite_on': 'Saved',
      'copy': 'Copy link',
      'share': 'Share',
      'open_wiki': 'Open Wikipedia',
      'text_up': 'Increase text',
      'text_down': 'Decrease text',
      'reader': 'Reading mode',
      'github': 'Author GitHub',
      'settings': 'Settings',
      'history': 'History',
      'favorites': 'Favorites',
      'empty_history': 'History is empty',
      'empty_favorites': 'No saved articles yet',
      'offline': 'No connection. Saved articles are available offline.',
      'try_again': 'Try again',
      'copied': 'Link copied',
      'app_language': 'App language',
      'wiki_language': 'Wikipedia language',
      'theme': 'App theme',
      'dark_theme': 'Dark theme',
      'stats': 'Statistics',
      'clear_history': 'Clear history',
      'clear_favorites': 'Clear favorites',
      'about': 'About app',
      'version': 'Yrysa Wiki Reader 2.82.47',
      'login': 'Sign in',
      'register': 'Create account',
      'guest': 'Continue as guest',
      'friends': 'Friends',
      'chats': 'Chats',
      'send_friend': 'Send to friend',
    },
    AppLanguage.kk: {
      'app': 'Yrysa Wiki Reader',
      'discover': 'Басты бет',
      'day': 'Күн мақаласы',
      'search': 'Іздеу',
      'saved': 'Сақталған',
      'social': 'Әлеумет',
      'profile': 'Профиль',
      'next': 'Келесі мақала',
      'favorite_add': 'Таңдаулыға қосу',
      'favorite_on': 'Таңдаулыда',
      'copy': 'Сілтемені көшіру',
      'share': 'Бөлісу',
      'open_wiki': 'Wikipedia ашу',
      'text_up': 'Мәтінді үлкейту',
      'text_down': 'Мәтінді кішірейту',
      'reader': 'Оқу режимі',
      'github': 'Автор GitHub',
      'settings': 'Баптаулар',
      'history': 'Тарих',
      'favorites': 'Таңдаулы',
      'empty_history': 'Тарих бос',
      'empty_favorites': 'Таңдаулы мақалалар жоқ',
      'offline': 'Интернет жоқ. Сақталған мақалалар оффлайн ашылады.',
      'try_again': 'Қайта көру',
      'copied': 'Сілтеме көшірілді',
      'app_language': 'Қолданба тілі',
      'wiki_language': 'Wikipedia тілі',
      'theme': 'Қолданба тақырыбы',
      'dark_theme': 'Қараңғы тақырып',
      'stats': 'Статистика',
      'clear_history': 'Тарихты тазалау',
      'clear_favorites': 'Таңдаулыны тазалау',
      'about': 'Қолданба туралы',
      'version': 'Yrysa Wiki Reader 2.82.47',
      'login': 'Кіру',
      'register': 'Аккаунт жасау',
      'guest': 'Қонақ ретінде кіру',
      'friends': 'Достар',
      'chats': 'Чаттар',
      'send_friend': 'Досқа жіберу',
    },
  };
}
